services:
  worker:
    volumes:
      - ./data/uploads:/data/uploads
      - ./data/audiobooks:/data/audiobooks
      - ./data/previews:/data/previews
      - ./data:/data
      - ./data/library:/mnt/openbooks:ro
  webapp:
    volumes:
      - ./data/uploads:/data/uploads
      - ./data/audiobooks:/data/audiobooks
      - ./data/previews:/data/previews
      - ./data:/data
      - ./data/library:/mnt/openbooks:ro
